### ISSUE TITLE
Timer duration is not displayed

### ISSUE THREAD

**Issue by Krocko** [e2m32/hass_custom_timer#2]
If I set an timer with a duration more then 24 hours (maybe 26 hours) it is displayed as 1 day 2 hours. If I start the timer, the duration is not displayed until it drops under 24 hours. With other words, only timer duration in hours is displayed. 
But the timer over 24 hours are converted to days and that would not be displayed. 
If I set the timer to 26 hours in the dev tools, it is displayed as 26 hours and it is working. 
I think it is related to #1.

**Comment by e2m32** [comment]
Hrm. I'll look into it. I wonder if the default version shows days.

**Comment by e2m32** [comment]
Just tested the default. It doesn't display days either. At least the version shipped with HA v0.103.6

**Comment by e2m32** [comment]
Version 0.104.2 has the same behavior. Wow! They changed a lot of stuff from 0.103 to 0.104... A lot of stuff I don't understand. It's going to take me a bit to merge this change.

**Comment by Krocko** [comment]
Thank you for investigation. Would be much appreciated if you find a fix.

**Comment by e2m32** [comment]
I was able to fix this in my latest commit, but it's based on 0.105. So you might want to wait until that release drops.
