### ISSUE TITLE
Restore don’t work if homekit is enabled

### ISSUE THREAD

**Issue by Krocko** [e2m32/hass_custom_timer#4]
Hi.
If I enable the HomeKit controller in the configuration the timer don’t work anymore.
If I restart ha, the timer is idle. 
Is this a known issue?

**Comment by Krocko** [comment]
It is working again. Don‘t know what was the problem.

**Comment by e2m32** [comment]
@Krocko, glad to hear that it's working. If it happens again, see if there is any information in the logs. I'd love to be able to recreate it to see what's going on. Thanks.  Cheers 🍻

**Comment by Krocko** [comment]
Thank you @e2m32. 
There was no error in the log.
