### ISSUE TITLE
Error with timer's services

### ISSUE THREAD

**Issue by Gferretta** [e2m32/hass_custom_timer#7]
Hi
I have installed following the full folder copy instructions.
Then restart the HA
And when it start, the Timer services do not appear (Start, Cancel, etc)
Any ideas?
This is exactly the tool that I am needing and I cannot get it to work with my scripts and automations.
I am using HA 2021.5.2

PS: Should the .gitignore file be copied to HA? It doesn't say anything in the instructions.

**Comment by WRoss7** [comment]
Hi Gferretta,
for the avoidance of doubt, here is the procedure: copy the contents of the custom_components folder, in the \ config \ custom_components folder of Home Assistant; if it doesn't exist, you have to create it.

Copy the following to Configuration.yaml:
[Allegato.odt](https://github.com/e2m32/hass_custom_timer/files/6518674/Allegato.odt)

Verify the configuration and if successful, restart the server

The service should now be available. If you still don't see it, try restarting the operating system

If it doesn't work like that, I can't help you.
If you need it, I can send you attached a complete guide that I wrote (in Italian). Let me know

**Comment by Gferretta** [comment]
Thanks

I probe it.

One question: timers defined  in Configuration -> Helpers, can stay or should all be removed previous reboot ?

My problem with this is that if i delete the timers it won't let me restart because i have automations and scripts where i use them  I do not know if I explain myself.  

Thank you.  

Regards

**Comment by WRoss7** [comment]
Hi,
the timers you configured in the configuration.yaml file must remain; if you remove them
and then restart the operating system (or even if you only restart Home Assistant), the service
it will not work.

The .gitignore file is not needed, it is only needed on the programming side: it is used to tell GitHub which project files to ignore

Ross

**Comment by Gferretta** [comment]
Hello
I followed all the steps that you have indicated, but when restarting the HA, the "Timers" services do not exist even having defined it in Configuration.Yaml.
The automations and scripts that I had defined using the services stop working and also give an error because they do not exist.
I really don't know why it happens.
The only thing to highlight is that I have timers defined in Configuration.Yaml and in Helpers.
I also appreciate your help.
Regards

![HA Timer Error](https://user-images.githubusercontent.com/65413059/119675745-b11c2580-be13-11eb-89b0-770d9e4c345a.jpg)

**Comment by WRoss7** [comment]
In the configuration.yaml file, did you enter "default_config:" as the first line?

![Yaml](https://user-images.githubusercontent.com/74879713/119724997-b3ac6880-be6f-11eb-948c-7f8eb52f9c1f.PNG)

**Comment by Gferretta** [comment]
> In the configuration.yaml file, did you enter "default_config:" as the first line?
> 
> ![Yaml](https://user-images.githubusercontent.com/74879713/119724997-b3ac6880-be6f-11eb-948c-7f8eb52f9c1f.PNG)

Yes.
Has a "default_config:" in the first few lines of Configuration.Yaml

**Comment by ryhanen** [comment]
I'm having similar issues. Seems to have something to do with how the timers are initialized:

> Error during setup of component timer
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 248, in _async_setup_component
>     result = await task
>   File "/config/custom_components/timer/__init__.py", line 147, in async_setup
>     await storage_collection.async_load()
>   File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 219, in async_load
>     await self.notify_changes(
>   File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 141, in notify_changes
>     await asyncio.gather(
>   File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 370, in _collection_changed
>     for entity in await asyncio.gather(
>   File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 336, in _add_entity
>     entities[change_set.item_id] = create_entity(change_set.item)
>   File "/config/custom_components/timer/__init__.py", line 227, in __init__
>     self._restore_grace_period = cv.time_period_str(
>   File "/usr/src/homeassistant/homeassistant/helpers/config_validation.py", line 383, in time_period_str
>     raise vol.Invalid("Make sure you wrap time values in quotes")
> voluptuous.error.Invalid: Make sure you wrap time values in quotes

**Comment by jofotoo** [comment]
Same here. Timer services are not available when this component is active. 
The timer i added to configuration.yaml appears and _looks_ functional ("start" button, attributes visible). However, the timers created in home assistant are unavailable and read-only; no start button.

Log on HA startup shows the same as ryhanen's system.
core-2021.8.5
supervisor-2021.06.8
Home Assistant OS 6.1
RPi3 running off SSD

**Comment by ciux23** [comment]
Hi, perhaps I found a solution:

1) you must to delete all you have in your "/config/.storage/timer". 
2) then write this:

{
    "version": 1,
    "key": "timer",
    "data": {
        "items": []
    }  (add 4 spaces)
}
![Schermata 2021-11-14 alle 13 27 46](https://user-images.githubusercontent.com/74420679/141681097-3c530092-2c1d-4ccf-940e-73c34df14ca1.png)

4) save
5) check configuration
6) restart HA
7) re-write your timers in yaml o by UI

if you use the UI the "restore" and the "restore_grace_period" options will be added automatically.

PS:
I'm Italian and my English is not good. Sorry
