### ISSUE TITLE
FYI - I am trying to bring this functionality into core

### ISSUE THREAD

**Issue by raman325** [e2m32/hass_custom_timer#8]
hey there, I wanted to let you know that I have resurrected your old PR (https://github.com/home-assistant/core/pull/28593) with some tweaks (see PR for more details https://github.com/home-assistant/core/pull/67658)

If you have any feedback on the approach I took, let me know! You can do it here or in the PR but to avoid polluting the PR with a discussion it may be better to discuss here

**Comment by raman325** [comment]
oops, linked the wrong PR, corrected

**Comment by raman325** [comment]
this is done!

**Comment by e2m32** [comment]
thanks for getting this merged 🎉very exciting!
